namespace Assets.Scripts.InputCustoms
{
    public class Vietnamese
    {
        public static string GetText(string text)
        {
            int length = text.Length;
            if (text.Length < 2)
            {
                return text;
            }
            return text.Substring(length - 2) switch
            {
                "as" => text.Substring(0, length - 2) + "á",
                "ás" => text.Substring(0, length - 2) + "as",
                "af" => text.Substring(0, length - 2) + "à",
                "àf" => text.Substring(0, length - 2) + "af",
                "ar" => text.Substring(0, length - 2) + "ả",
                "ảr" => text.Substring(0, length - 2) + "ar",
                "ax" => text.Substring(0, length - 2) + "ã",
                "ãx" => text.Substring(0, length - 2) + "ax",
                "aj" => text.Substring(0, length - 2) + "ạ",
                "ạj" => text.Substring(0, length - 2) + "aj",
                "aw" => text.Substring(0, length - 2) + "ă",
                "ăw" => text.Substring(0, length - 2) + "aw",
                "ăs" => text.Substring(0, length - 2) + "ắ",
                "ắs" => text.Substring(0, length - 2) + "ăs",
                "ăf" => text.Substring(0, length - 2) + "ằ",
                "ằf" => text.Substring(0, length - 2) + "ăf",
                "ăr" => text.Substring(0, length - 2) + "ẳ",
                "ẳr" => text.Substring(0, length - 2) + "ăr",
                "ăx" => text.Substring(0, length - 2) + "ẵ",
                "ẵ" => text.Substring(0, length - 2) + "ăx",
                "ăj" => text.Substring(0, length - 2) + "ặ",
                "ặj" => text.Substring(0, length - 2) + "ăj",
                "aa" => text.Substring(0, length - 2) + "â",
                "âa" => text.Substring(0, length - 2) + "aa",
                "âs" => text.Substring(0, length - 2) + "ấ",
                "ấs" => text.Substring(0, length - 2) + "âs",
                "âf" => text.Substring(0, length - 2) + "ầ",
                "ầf" => text.Substring(0, length - 2) + "âf",
                "âr" => text.Substring(0, length - 2) + "ẩ",
                "ẩr" => text.Substring(0, length - 2) + "âr",
                "âx" => text.Substring(0, length - 2) + "ẫ",
                "ẫx" => text.Substring(0, length - 2) + "âx",
                "âj" => text.Substring(0, length - 2) + "ậ",
                "ậj" => text.Substring(0, length - 2) + "âj",
                "es" => text.Substring(0, length - 2) + "é",
                "és" => text.Substring(0, length - 2) + "es",
                "ef" => text.Substring(0, length - 2) + "è",
                "èf" => text.Substring(0, length - 2) + "ef",
                "er" => text.Substring(0, length - 2) + "ẻ",
                "ẻr" => text.Substring(0, length - 2) + "er",
                "ex" => text.Substring(0, length - 2) + "ẽ",
                "ẽx" => text.Substring(0, length - 2) + "ex",
                "ej" => text.Substring(0, length - 2) + "ẹ",
                "ẹj" => text.Substring(0, length - 2) + "ej",
                "ee" => text.Substring(0, length - 2) + "ê",
                "êe" => text.Substring(0, length - 2) + "ee",
                "ês" => text.Substring(0, length - 2) + "ế",
                "ếs" => text.Substring(0, length - 2) + "ês",
                "êf" => text.Substring(0, length - 2) + "ề",
                "ềf" => text.Substring(0, length - 2) + "êf",
                "êr" => text.Substring(0, length - 2) + "ể",
                "ểr" => text.Substring(0, length - 2) + "êr",
                "êx" => text.Substring(0, length - 2) + "ễ",
                "ễx" => text.Substring(0, length - 2) + "êx",
                "êj" => text.Substring(0, length - 2) + "ệ",
                "ệj" => text.Substring(0, length - 2) + "êj",
                "is" => text.Substring(0, length - 2) + "í",
                "ís" => text.Substring(0, length - 2) + "is",
                "if" => text.Substring(0, length - 2) + "ì",
                "ìf" => text.Substring(0, length - 2) + "if",
                "ir" => text.Substring(0, length - 2) + "ỉ",
                "ỉr" => text.Substring(0, length - 2) + "ir",
                "ix" => text.Substring(0, length - 2) + "ĩ",
                "ĩx" => text.Substring(0, length - 2) + "ix",
                "ij" => text.Substring(0, length - 2) + "ị",
                "ịj" => text.Substring(0, length - 2) + "ij",
                "os" => text.Substring(0, length - 2) + "ó",
                "ós" => text.Substring(0, length - 2) + "os",
                "of" => text.Substring(0, length - 2) + "ò",
                "òf" => text.Substring(0, length - 2) + "of",
                "or" => text.Substring(0, length - 2) + "ỏ",
                "ỏr" => text.Substring(0, length - 2) + "or",
                "ox" => text.Substring(0, length - 2) + "õ",
                "õx" => text.Substring(0, length - 2) + "ox",
                "oj" => text.Substring(0, length - 2) + "ọ",
                "ọj" => text.Substring(0, length - 2) + "oj",
                "oo" => text.Substring(0, length - 2) + "ô",
                "ôo" => text.Substring(0, length - 2) + "oo",
                "ôs" => text.Substring(0, length - 2) + "ố",
                "ốs" => text.Substring(0, length - 2) + "ôs",
                "ôf" => text.Substring(0, length - 2) + "ồ",
                "ồf" => text.Substring(0, length - 2) + "ôf",
                "ôr" => text.Substring(0, length - 2) + "ổ",
                "ổr" => text.Substring(0, length - 2) + "ôr",
                "ôx" => text.Substring(0, length - 2) + "ỗ",
                "ỗx" => text.Substring(0, length - 2) + "ôx",
                "ôj" => text.Substring(0, length - 2) + "ộ",
                "ộj" => text.Substring(0, length - 2) + "ôj",
                "ow" => text.Substring(0, length - 2) + "ơ",
                "ơw" => text.Substring(0, length - 2) + "ow",
                "ơs" => text.Substring(0, length - 2) + "ớ",
                "ớs" => text.Substring(0, length - 2) + "ơs",
                "ơf" => text.Substring(0, length - 2) + "ờ",
                "ờf" => text.Substring(0, length - 2) + "ơf",
                "ơr" => text.Substring(0, length - 2) + "ở",
                "ởr" => text.Substring(0, length - 2) + "ơr",
                "ơx" => text.Substring(0, length - 2) + "ỡ",
                "ỡx" => text.Substring(0, length - 2) + "ơx",
                "ơj" => text.Substring(0, length - 2) + "ợ",
                "ợj" => text.Substring(0, length - 2) + "ơj",
                "us" => text.Substring(0, length - 2) + "ú",
                "ús" => text.Substring(0, length - 2) + "us",
                "uf" => text.Substring(0, length - 2) + "ù",
                "ùf" => text.Substring(0, length - 2) + "uf",
                "ur" => text.Substring(0, length - 2) + "ủ",
                "ủr" => text.Substring(0, length - 2) + "ur",
                "ux" => text.Substring(0, length - 2) + "ũ",
                "ũx" => text.Substring(0, length - 2) + "ux",
                "uj" => text.Substring(0, length - 2) + "ụ",
                "ụj" => text.Substring(0, length - 2) + "uj",
                "uw" => text.Substring(0, length - 2) + "ư",
                "ưw" => text.Substring(0, length - 2) + "uu",
                "ưs" => text.Substring(0, length - 2) + "ứ",
                "ứs" => text.Substring(0, length - 2) + "ưs",
                "ưf" => text.Substring(0, length - 2) + "ừ",
                "ừf" => text.Substring(0, length - 2) + "ưf",
                "ưr" => text.Substring(0, length - 2) + "ử",
                "ửr" => text.Substring(0, length - 2) + "ưr",
                "ưx" => text.Substring(0, length - 2) + "ữ",
                "ữx" => text.Substring(0, length - 2) + "ưx",
                "ưj" => text.Substring(0, length - 2) + "ự",
                "ựj" => text.Substring(0, length - 2) + "ưj",
                "ys" => text.Substring(0, length - 2) + "ý",
                "ýs" => text.Substring(0, length - 2) + "ys",
                "yf" => text.Substring(0, length - 2) + "ỳ",
                "ỳf" => text.Substring(0, length - 2) + "yf",
                "yr" => text.Substring(0, length - 2) + "ỷ",
                "ỷr" => text.Substring(0, length - 2) + "yr",
                "yx" => text.Substring(0, length - 2) + "ỹ",
                "ỹx" => text.Substring(0, length - 2) + "yx",
                "yj" => text.Substring(0, length - 2) + "ỵ",
                "ỵj" => text.Substring(0, length - 2) + "yj",
                "dd" => text.Substring(0, length - 2) + "đ",
                "đd" => text.Substring(0, length - 2) + "dd",
                _ => text,
            };
        }
    }
}
